captainVersion: 4
caproverOneClickApp:
    instructions:
        start: Just a simple Docker Compose one click app with app, api and db.
        end: $$cap_appname is deployed. 😄
    variables:
        - id: $$cap_postgres_user
          label: Postgres user
          defaultValue: 'postgres'
        - id: $$cap_postgres_password
          label: Postgres password
          defaultValue: 'postgres'
        - id: $$cap_postgress_db
          label: Postgres DB
          defaultValue: 'test_db'
        - id: $$cap_api_image_tag
          label: simple-api image tag
          defaultValue: '0.0.5'
          description: Check the page for more info https://hub.docker.com/repository/docker/andresabadia/simple-api
        - id: $$cap_app_image_tag
          label: frontend-simple-api image tag
          defaultValue: '0.0.3'
          description: Check the page for more info https://hub.docker.com/repository/docker/andresabadia/frontend-simple-api
    displayName: A simple App
    isOfficial: false
    description: This is a simple testing app. It contains an Vue Frontend, Express Backend and postgres DB.
########
version: '3'
services:
    $$cap_appname-db:
        image: postgres
        volumes:
            - $$cap_appname-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: $$cap_postgres_user
            POSTGRES_PASSWORD: $$cap_postgres_password
            POSTGRES_DB: $$cap_postgress_db
        caproverExtra:
            notExposeAsWebApp: 'true'
    $$cap_appname-api:
        depends_on:
            - $$cap_appname-db
        image: 'andresabadia/simple-api:$$cap_api_image_tag'
        environment:
            DB_HOST: srv-captain--$$cap_appname-db
            DB_NAME: $$cap_postgress_db
            DB_USERNAME: $$cap_postgres_user
            DB_PASSWORD: $$cap_postgres_password
        caproverExtra:
            containerHttpPort: '3004'
    $$cap_appname-app:
        depends_on:
            - $$cap_appname-api
        image: 'andresabadia/frontend-simple-api:$$cap_app_image_tag'
        environment:
            API_HOST: srv-captain--$$cap_appname-api
        caproverExtra:
            containerHttpPort: '80'
volumes:
    $$cap_appname-data:
